### ISSUE TITLE
CSS not loaded

### ISSUE THREAD

**Issue by ctanas** [tonyaldon/one.el#4]
The generated HTML file has the following: `<link rel="stylesheet" type="text/css" href="/one.css" />`, thus the one.css file in the current folder is not loaded when the HTML file is opened in the browser. Maybe the above line should look like this? `<link rel="stylesheet" type="text/css" href="/one.css" />` (without the slash?)

**Comment by tonyaldon** [comment]
Hi @ctanas, thank you for giving a try to `one.el`.

Correct me if I'm wrong but I think that you opened the main `index.html` generated in the `public` directory by `one.el` with your browser as a regular file not by visiting a local url like `http://localhost:3000` for instance.

If this is the case, you should try to start a web server in the `public` directory that serves the files in the directory.  And then visiting a local url.  This can be done for instance with `browser-sync` utility running the following command (inside the `public` directory):

    browser-sync start -s -w --files "*"

See <https://one.tonyaldon.com/docs/getting-started/> and also the first 10 minutes of my talk at EmacsConf 2023 <https://one.tonyaldon.com>.

Please tell me if this work for you!

**Comment by ctanas** [comment]
You are right! Followed your advice and it works!

**Comment by tonyaldon** [comment]
Cool to hear that!
